config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'articles/new'
  get 'articles/create'
  get 'articles/show'
  get 'articles/edit'
  get 'articles/update'
  get 'articles/destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :text
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles#index</h1>

app/views/articles/new.html.erb
<h1>Articles new</h1>
  <%= form_with scope: :article, url: articles_new_path, local: true do |form| %>
    <p>
      <%= form.label :title %>
      <br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :text %>
      <br>
      <%= form.rich_text_area :text  %>
    </p>
    <p>
      <%= form.submit %>
      <br>
    </p>
  <% end %>
<p>End of form</p>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<h1>Articles title:</h1>
<p><strong><%= @article.title %></strong></p>
<h1>Articles text:</h1>
<p><strong><%= @article.text %></strong></p>
<%= link_to 'Create new', new_article_path %>
<p></p>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionTextExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>